import type { CSSProperties } from "react";

/** Co-located styles for PreviewStep. Paths are unbroken mono strings, so every
 *  container that can hold one sets `minWidth: 0` and wraps with
 *  `overflowWrap: "anywhere"` (client INSIGHTS 2026-09-24). */
export const s = {
  split: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 240px) minmax(0, 1fr)",
    gap: 12,
    minWidth: 0,
  } satisfies CSSProperties,
  listPane: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    minWidth: 0,
    padding: 10,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  listLabel: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.03em",
    color: "var(--text-muted)",
    padding: "2px 6px 8px",
  } satisfies CSSProperties,
  fileItem: (active: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    width: "100%",
    minWidth: 0,
    textAlign: "left",
    padding: "7px 8px",
    borderRadius: 6,
    border: "none",
    background: active ? "var(--accent-bg)" : "transparent",
    color: active ? "var(--accent-text)" : "var(--text-secondary)",
    fontSize: 12.5,
    cursor: "pointer",
  }),
  fileIcon: { flexShrink: 0, marginTop: 2 } satisfies CSSProperties,
  filePath: { minWidth: 0, overflowWrap: "anywhere" } satisfies CSSProperties,
  viewer: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    overflow: "hidden",
  } satisfies CSSProperties,
  viewerHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    minWidth: 0,
    padding: "9px 12px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  viewerPath: {
    flex: 1,
    minWidth: 0,
    fontSize: 12.5,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  editableBadge: { flexShrink: 0 } satisfies CSSProperties,
  editor: {
    width: "100%",
    minHeight: 300,
    resize: "vertical",
    padding: 12,
    border: "none",
    outline: "none",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
    fontSize: 12,
    lineHeight: 1.55,
    whiteSpace: "pre",
    overflow: "auto",
  } satisfies CSSProperties,
  pre: {
    margin: 0,
    padding: 12,
    minHeight: 120,
    maxHeight: 340,
    overflow: "auto",
    fontSize: 12,
    lineHeight: 1.55,
    background: "var(--bg-elevated)",
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  runnerBox: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: 12,
    fontSize: 13,
    minWidth: 0,
  } satisfies CSSProperties,
  hash: { fontSize: 12, color: "var(--text-secondary)", overflowWrap: "anywhere" } satisfies CSSProperties,
  runnerNote: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  warning: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    fontSize: 12.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  warningText: { minWidth: 0, overflowWrap: "anywhere" } satisfies CSSProperties,
  lint: {
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--crit)",
    background: "var(--bg-surface)",
    fontSize: 12.5,
  } satisfies CSSProperties,
  lintTitle: { fontWeight: 600, color: "var(--crit)", marginBottom: 6 } satisfies CSSProperties,
  lintList: { margin: 0, paddingLeft: 18, display: "flex", flexDirection: "column", gap: 4 } satisfies CSSProperties,
  lintItem: { fontSize: 12, overflowWrap: "anywhere" } satisfies CSSProperties,
} as const;
