import type { CSSProperties } from "react";
import { PANEL_WIDTH } from "./constants";

export const s = {
  root: { position: "relative", display: "inline-block" } satisfies CSSProperties,
  panel: {
    position: "absolute",
    top: "calc(100% + 6px)",
    right: 0,
    width: PANEL_WIDTH,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-strong)",
    borderRadius: 9,
    boxShadow: "var(--shadow-modal)",
    zIndex: 40,
  } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 14px 6px",
  } satisfies CSSProperties,
  title: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.06em",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  clear: {
    background: "none",
    border: "none",
    padding: 0,
    fontSize: 12,
    fontWeight: 600,
    color: "var(--accent)",
    cursor: "pointer",
  } satisfies CSSProperties,
  list: { padding: "0 6px 6px" } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 8px",
    borderRadius: 6,
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
  } satisfies CSSProperties,
  name: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  estimate: { fontSize: 12, color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  empty: { padding: "8px 14px 12px", fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  runWrap: { padding: 10, borderTop: "1px solid var(--border)" } satisfies CSSProperties,
  error: {
    margin: "0 10px 10px",
    padding: "8px 10px",
    borderRadius: 6,
    fontSize: 12.5,
    color: "var(--crit)",
    background: "var(--crit-bg)",
    wordBreak: "break-word",
  } satisfies CSSProperties,
  errorLink: {
    display: "block",
    marginTop: 4,
    background: "none",
    border: "none",
    padding: 0,
    font: "inherit",
    fontWeight: 600,
    color: "var(--accent)",
    textDecoration: "underline",
    cursor: "pointer",
  } satisfies CSSProperties,
  configure: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    padding: "10px 14px",
    border: "none",
    borderTop: "1px solid var(--border)",
    background: "transparent",
    color: "var(--text-secondary)",
    fontSize: 13,
    textAlign: "left",
    cursor: "pointer",
  } satisfies CSSProperties,
};
