import type { CSSProperties } from "react";

const wrap: CSSProperties = { overflowWrap: "anywhere", wordBreak: "break-word", minWidth: 0 };

export const s = {
  card: (accent: string): CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderTop: `2px solid ${accent}`,
    borderRadius: 10,
    overflow: "hidden",
  }),
  header: { display: "flex", alignItems: "center", gap: 10, padding: 12, minWidth: 0 } satisfies CSSProperties,
  iconBox: (accent: string): CSSProperties => ({
    width: 32,
    height: 32,
    borderRadius: 8,
    flexShrink: 0,
    display: "grid",
    placeItems: "center",
    color: accent,
    background: `color-mix(in srgb, ${accent} 15%, transparent)`,
  }),
  headMain: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  name: { fontSize: 14, fontWeight: 600, color: "var(--text-primary)", ...wrap } satisfies CSSProperties,
  meta: { fontSize: 11.5, color: "var(--text-muted)" } satisfies CSSProperties,
  body: { display: "flex", flexDirection: "column", gap: 8, padding: "0 12px 12px", flex: 1, minHeight: 120, minWidth: 0 } satisfies CSSProperties,
  item: (color: string): CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    gap: 6,
    minWidth: 0,
    padding: "8px 10px",
    background: "var(--bg-base, var(--bg-hover))",
    border: "1px solid var(--border)",
    borderLeft: `3px solid ${color}`,
    borderRadius: 6,
  }),
  itemBtn: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    background: "none",
    border: "none",
    padding: 0,
    textAlign: "left",
    cursor: "pointer",
    color: "inherit",
    minWidth: 0,
  } satisfies CSSProperties,
  itemTitleRow: { display: "flex", alignItems: "center", gap: 8, minWidth: 0 } satisfies CSSProperties,
  itemTitle: { fontSize: 13, fontWeight: 600, color: "var(--text-primary)", ...wrap } satisfies CSSProperties,
  itemLoc: { fontSize: 11.5, color: "var(--text-muted)", ...wrap } satisfies CSSProperties,
  empty: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    padding: "10px 12px",
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  traceBtn: {
    background: "none",
    border: "none",
    padding: 0,
    cursor: "pointer",
    color: "var(--text-secondary)",
    fontSize: 12.5,
  } satisfies CSSProperties,
  count: { fontSize: 12, color: "var(--text-muted)", display: "inline-flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
};
