import type { CSSProperties } from "react";

/** Co-located styles for the SkillEditor shell. */
export const s = {
  wrap: { display: "flex", flexDirection: "column", gap: 0 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 10, marginBottom: 10, flexWrap: "wrap" } satisfies CSSProperties,
  iconTile: {
    width: 30,
    height: 30,
    borderRadius: 8,
    background: "var(--bg-hover)",
    color: "var(--accent)",
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
  } satisfies CSSProperties,
  // Long skill names wrap instead of pushing the actions off-screen (client/INSIGHTS.md 2026-09-24).
  h2: { fontSize: 20, fontWeight: 700, minWidth: 0, overflowWrap: "anywhere", wordBreak: "break-word" } satisfies CSSProperties,
  headerActions: { marginLeft: "auto", display: "flex", alignItems: "center", gap: 8, flexShrink: 0 } satisfies CSSProperties,
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    overflow: "hidden",
    clip: "rect(0 0 0 0)",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  untrustedNotice: {
    fontSize: 12.5,
    color: "var(--warn)",
    background: "var(--warn-bg, rgba(234,179,8,0.1))",
    border: "1px solid var(--warn)",
    borderRadius: 8,
    padding: "10px 12px",
    lineHeight: 1.5,
    marginBottom: 14,
  } satisfies CSSProperties,
  tabsBar: { margin: "0 -24px" } satisfies CSSProperties,
  body: { paddingTop: 18 } satisfies CSSProperties,
  scanAlert: {
    background: "var(--crit-bg, rgba(239,68,68,0.1))",
    border: "1px solid var(--crit)",
    borderRadius: 8,
    padding: "10px 12px",
    marginBottom: 14,
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
  scanAlertHeader: { display: "flex", alignItems: "center" } satisfies CSSProperties,
  findingsList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
  findingItem: {
    borderTop: "1px solid var(--border)",
    paddingTop: 10,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  findingHeader: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  findingCategory: { fontSize: 12, color: "var(--text-secondary)", fontWeight: 600 } satisfies CSSProperties,
  findingExcerpt: {
    margin: 0,
    padding: "6px 10px",
    borderLeft: "2px solid var(--border)",
    fontSize: 12.5,
    fontFamily: "var(--font-mono, monospace)",
    color: "var(--text-secondary)",
    whiteSpace: "pre-wrap",
  } satisfies CSSProperties,
  findingExplanation: { fontSize: 13, lineHeight: 1.5 } satisfies CSSProperties,
  findingLocation: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
