import type { CSSProperties } from "react";

/** Co-located styles for EvalsTab. */
export const s = {
  wrap: { display: "flex", flexDirection: "column", gap: 24, maxWidth: 900 } satisfies CSSProperties,
  metricsHeader: { display: "flex", alignItems: "center", gap: 8, marginBottom: 12 } satisfies CSSProperties,
  metricsLabel: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  dashLink: {
    marginLeft: "auto",
    fontSize: 12.5,
    color: "var(--text-secondary)",
    textDecoration: "none",
  } satisfies CSSProperties,
  tileRow: { display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", gap: 14 } satisfies CSSProperties,
  tile: {
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 9,
    padding: "14px 16px",
    minWidth: 0,
  } satisfies CSSProperties,
  tileLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 8,
  } satisfies CSSProperties,
  tileValueRow: { display: "flex", alignItems: "baseline", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  note: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    marginTop: 12,
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 10, marginBottom: 12, flexWrap: "wrap" } satisfies CSSProperties,
  sectionTitle: { fontSize: 16, fontWeight: 700 } satisfies CSSProperties,
  chip: (color: string): CSSProperties => ({
    fontSize: 12,
    fontWeight: 600,
    color,
    background: "var(--bg-hover)",
    borderRadius: 5,
    padding: "2px 9px",
  }),
  headerActions: { marginLeft: "auto", display: "flex", gap: 8 } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  rowIcon: { flexShrink: 0, display: "grid", placeItems: "center", width: 20 } satisfies CSSProperties,
  // minWidth 0 + wrapping so long names / file:line summaries never push the row wider (client/INSIGHTS.md 2026-09-24).
  rowMain: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  rowTitleLine: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap", minWidth: 0 } satisfies CSSProperties,
  rowName: {
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
    overflowWrap: "anywhere",
    wordBreak: "break-word",
    minWidth: 0,
  } satisfies CSSProperties,
  kindBadge: (color: string): CSSProperties => ({
    fontSize: 10.5,
    fontWeight: 700,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color,
    border: `1px solid ${color}`,
    borderRadius: 4,
    padding: "1px 6px",
    whiteSpace: "nowrap",
  }),
  rowSummary: {
    fontSize: 12.5,
    color: "var(--text-muted)",
    marginTop: 2,
    overflowWrap: "anywhere",
    wordBreak: "break-word",
    minWidth: 0,
  } satisfies CSSProperties,
  rowChip: {
    fontSize: 12,
    color: "var(--text-muted)",
    background: "var(--bg-hover)",
    borderRadius: 5,
    padding: "3px 9px",
    whiteSpace: "nowrap",
    flexShrink: 0,
  } satisfies CSSProperties,
  rowActions: { display: "flex", gap: 2, flexShrink: 0 } satisfies CSSProperties,
} as const;
